Repository saltastroops/nir-simulator, pull requests merged in 2024-01, with the labels that each got.

#65 Documentation
  .dockerignore
  .gitignore
  README.md
  backend/.dockerignore
  backend/nirwals/physics/bandpass.py
  backend/nirwals/physics/exposure.py
  backend/nirwals/physics/spectrum.py
  backend/nirwals/physics/utils.py
  backend/requirements.txt
  deployment/Dockerfile-backend
  deployment/Dockerfile-documentation
  deployment/Dockerfile-frontend
  deployment/Dockerfile-router
  deployment/deploy-simulator.sh
  deployment/docker-compose.yml
  deployment/nginx-documentation.conf
  deployment/nginx-frontend.conf
  deployment/nginx-router.conf
  docker-compose.yml
  documentation/docs/assets/favicon.png
  documentation/docs/assets/logo-salt.png
  documentation/docs/css/mkdocstrings.css
  documentation/docs/images/configure-nirwals-tab.png
  documentation/docs/images/delete-spectrum.png
  documentation/docs/images/generate-spectrum-tab.png
  documentation/docs/images/make-an-exposure-tab.png
  documentation/docs/images/nirwals-first-light.jpg
  documentation/docs/images/salt-moving-pupil.png
  documentation/docs/images/sliding-window.png
  documentation/docs/index.md
  documentation/docs/javascripts/katex.js
  documentation/docs/python-code/index.md
  documentation/docs/python-code/nirwals.physics.bandpass.md
  documentation/docs/python-code/nirwals.physics.exposure.md
  documentation/docs/python-code/nirwals.physics.spectrum.md
  documentation/docs/python-code/nirwals.physics.utils.md
  documentation/docs/simulator-physics.md
  documentation/docs/user-manual.md
  documentation/mkdocs.yml
  router/.dockerignore
Labels: documentation

#82 Update expected filter name
  backend/nirwals/configuration.py
Labels: bug

#80 Add "with emission lines" property for galaxy source
  backend/nirwals/configuration.py
  frontend/src/components/spectrum/GalaxyPanel.tsx
Labels: enhancement, technical debt
